---
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - 8090:8090/tcp
#     - 8080:8080
#     - 6881:6881
#     - 32400:32400
    volumes:
      - ./gluetun:/gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=USERNAME
      - OPENVPN_PASSWORD=PASSWORD
      - SERVER_REGION=us-florida.privacy.network
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24,172.20.0.0/16,192.168.0.0/24
      - UPDATER_PERIOD=24h
    labels:
      - com.centurylinklabs.watchtower.enable=false
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8090
      - UMASK=022
    volumes:
      - ./config:/config
      - /mnt/storage/downloads:/downloads
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

#  pms-docker:
#    container_name: plex
#    network_mode: service:gluetun
#    environment:
#      - TZ=America/New_York
#      - PLEX_CLAIM=claim-nDn9-vbpvPsGfnJw3ndN
#    volumes:
#      - ./config:/config
#      - ./transcode:/transcode
#      - /mnt/storage/media:/data
#    image: plexinc/pms-docker
#    depends_on:
#      gluetun:
#        condition: service_healthy
#    restart: unless-stopped
